### ISSUE TITLE
No material and bones are objects

### ISSUE THREAD

**Issue by 09williamsad** [AsteriskAmpersand/Mod3-MHW-Importer#1]
Blender version: 2.79b 2018-3-22 14:10
Importer version: latest as of 12:00 GMT 1 today
MHW game version: 167589

Issue:
When importing any extracted .mod3 file the model has no material and the armature made of objects instead of bones.
![image](https://user-images.githubusercontent.com/23011550/59507042-b7709b80-8ea1-11e9-874c-7d3d1a5b56a0.png)

This is not the case for the outdated TheCrazyT BlenderMhwModelImporter which gets the skeleton and a single material (joins multiple materials into one with broken UVs).

.mod3 file with fbx conversions for Mod3-MHW-Importer and BlenderMhwModelImporter versions
[pl036_0000 Arm.zip](https://github.com/AsteriskAmpersand/Mod3-MHW-Importer/files/3290449/pl036_0000.Arm.zip)

**Comment by AsteriskAmpersand** [comment]
Not a bug. It's covered in the wiki documentation linked in the README. MOD3 skeletal structure is not equivalent to a blender skeleton, as a result EMPTY nubs are used instead to preserve fidelity to the file structure. It's possible to approximate with a skeleton but it loses important data in the process, there's a script for one way conversion of the tree of empties to a skeleton (might require minor edits if you intend it to be a rigging for another program).

I don't understand the material complaint. The mod3 format doesn't have materials, only geometry data and mesh properties that link to the actual materials file mrl3. The mrl3 materials are not equivalent to any standard material format or structure and reference MTFramework propietary shaders. The current importer is able to properly load UV Maps and in the case of models with multiple UV Maps create them correctly (and save them back). If you want dummy materials you can create them yourself, they are not part of the mod3 specification and wouldn't be storable back in the mod3 format regardless.

All of this is covered in one way or another on the linked wiki articles.
