### ISSUE TITLE
Merged hand weights

### ISSUE THREAD

**Issue by 09williamsad** [AsteriskAmpersand/Mod3-MHW-Importer#10]
When imported using the latest release m_arm050_0500 has merged weights on the right fingers resulting the movement of one finger pulling the mesh of another.
![Capture](https://user-images.githubusercontent.com/23011550/73880644-b6d4ad00-4856-11ea-8be5-443e9fd6c462.JPG)
![image](https://user-images.githubusercontent.com/23011550/73880841-1b900780-4857-11ea-960d-1a3272d16212.png)
[m_arm050_0500.zip](https://github.com/AsteriskAmpersand/Mod3-MHW-Importer/files/4161939/m_arm050_0500.zip)
This is with the skeleton set to animation armature and weights set to standard.
I tested a few other arms and they worked fine so it may be just this model.

Update:
After more checking I have found that the legs of the savage deviljho armour, barioth arms and various chest armour has mixed weights aswell.

**Comment by AsteriskAmpersand** [comment]
Read the modding wiki entry about negative weights and split slash notation.

**Comment by 09williamsad** [comment]
I have read the wiki page and tried the other weight options but they result in the mesh not being weighted to the skeleton.

Additionally I tried the MT Framework 3ds max importer and for some models it does not have this issue, see the attached for the barioth male Beta armour fbx files for both importers.
![Untitled](https://user-images.githubusercontent.com/23011550/74252412-93da4b00-4ce5-11ea-8852-6669390a3962.png)
[Barioth blender and max.zip](https://github.com/AsteriskAmpersand/Mod3-MHW-Importer/files/4186546/Barioth.blender.and.max.zip)
https://lukascone.wordpress.com/2017/06/18/mt-framework-tools/
