### ISSUE TITLE
Blender Installation Issues

### ISSUE THREAD

**Issue by MHWModder** [AsteriskAmpersand/Mod3-MHW-Importer#11]
Attempting to install the add-on just results in a error saying Blender 2.8x is needed, despite currently being on Blender 2.82

![Capture1](https://user-images.githubusercontent.com/61105397/74600711-38dc8700-504a-11ea-993f-bad0956a3dc6.PNG)

Downloading the file using the 1.5v instead gives an error relating to a module

![Capture](https://user-images.githubusercontent.com/61105397/74600705-295d3e00-504a-11ea-95a1-60219d0f5052.PNG)

![Capture2](https://user-images.githubusercontent.com/61105397/74600706-2bbf9800-504a-11ea-9f00-cf889c9dafac.PNG)

**Comment by AsteriskAmpersand** [comment]
Plugin is for 2.79

**Comment by luxalpa** [comment]
Can this be documented? I installed blender just for this plugin, now I have to uninstall it and find a different version ... ?
