### ISSUE TITLE
Exporting models rigged using an armature

### ISSUE THREAD

**Issue by Ryuu-Risto** [AsteriskAmpersand/Mod3-MHW-Importer#12]
I have attempted to replace an NPC's model with a monster's model, and I've hit a wall in regards of actually making it look somewhat correct.

In order to make the model fit a humane shape, I need to manipulate it's mesh and rig a bit.
I've attempted bending the mesh using hooks between the empty nodes and vertex groups, but pretty much any bone rotation results in extreme warping of the model.
That issue doesn't happen when the model is imported with an armature, as from what I understand, the joints have physical size that prevents the mesh from warping and folding out of existence.
Unfortunately this plugin doesn't appear to be able to export such an armature as a rig for the mod3 format, which at this point pretty much forces me to do some mesh + armature + empty rig shenanigans in order to both be able to modify the model properly and export it into .mod3.

(Would also be nice if this plugin was made compatible with blender 2.92)

**Comment by AsteriskAmpersand** [comment]
There's a tutorial by Statyk on working with humanoid models and with armatures for those.
https://www.youtube.com/watch?v=4UFeFKohgpE

Compatibility for 2.92 will not happen, API differences are too big and there's no benefits from the API side to updating it (no API change that simplifies the back-end code, no better debugging, no better normal handling, etc). The repository is free to be forked but this will remain a 2.79 tool, and all other MHW modelling tools (Mod3 Toolbox, CTC/CCL Editors, VM Editor) are also 2.79, all of those would have to be updated as well.
