### ISSUE TITLE
Unavailable for 3.1

### ISSUE THREAD

**Issue by keybladegames** [AsteriskAmpersand/Mod3-MHW-Importer#16]
Tried installing multiple times, it shows up on the list as installed and yet when I go to import or export it doesnt appear. I tried 2.7, 2.8, 2.8.3 and even 2.9 and all it does is tell me I need 2.8X. Tried again on 3.1 and STILL doesnt appear.

please please PLEASE update it for 3.1

**Comment by AsteriskAmpersand** [comment]
No.
