### ISSUE TITLE
Importer not even appearing

### ISSUE THREAD

**Issue by keybladegames** [AsteriskAmpersand/Mod3-MHW-Importer#18]
I tried going to the addon tab to install it, I dragged the file into the addon folder and it wont turn on. I keep getting something called a traceback error or whatever. I tried the modern version and an older version of blender and I STILL can't get it to work

**Comment by LyraMoonDev** [comment]
Please read the README..
Install Blender `2.79` and try again

**Comment by DigitalxGoon** [comment]
> Please read the README.. Install Blender `2.79` and try again

Not trying to be rude, but that isn't helpful at all. I've read the "README" which doesnt tell me much of anything at all. I've re-installed Blender 2.79 and copied the files over into a folder I created in the addon folder, and the importer still does not appear.

**Comment by Chris-DF** [comment]
Why this ticket still OPEN, you guys should learn how to use blender addons first.
There’s no this issue for sure.

**Comment by fynnonymus** [comment]
For anyone having the same issue make sure your file structure looks like this:
2.79
     L Scripts
                 L addons
                              L Mod3-MHW-Importer-master
                                                                                L __init__.py (and all the other files from the zip)

It fixed the same problem for me so i hope this helps.
