### ISSUE TITLE
2.8 Update

### ISSUE THREAD

**Issue by AsteriskAmpersand** [AsteriskAmpersand/Mod3-MHW-Importer#5]
bpy.types.INFO_MT_file_import ---> bpy.types.TOPBAR_MT_file_import
bpy.types.INFO_MT_file_export ---> bpy.types.TOPBAR_MT_file_export
bpy.context.scene.objects ---> bpy.context.scene.collection.objects
blenderMesh.uv_textures ---> blenderMesh.uv_layers
Explicitly pass arguments for the new() function
vertex_groups.new(groupName) ---> vertex_groups.new(name=groupName)
uv_textures.new(name) ---> blenderMesh.uv_layers.new(name=name)
And comment out basically anything related to QoL rendering like show_edge_sharp and show_x_ray

**Comment by Elvyria** [comment]
If you're ok with changes in my fork, i can send PR you need it.
https://github.com/Elvyria/Mod3-MHW-Importer/commit/d37012b30a55b2ec22e91192a8e8afe826737ea8

**Comment by AsteriskAmpersand** [comment]
Looks good to me, PR and I'll accept it. Tyvm!
